[build]
builder = "nixpacks"

[deploy]
startCommand = "pnpm prisma migrate deploy && pnpm start:prod"
healthcheckPath = "/api"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
